# Generated by Django 5.0.3 on 2024-03-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='crearted_at',
            new_name='created_at',
        ),
    ]
